/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.math.BigDecimal;

import static org.junit.Assert.*;

public class RpnCalculatorHandlerTest {

    @Test
    public void testAddNumbers() {
        RpnCalculatorHandler calHandler = new RpnCalculatorHandler();

        calHandler.processInput( "12", 1 );
        calHandler.processInput( "34", 2 );
        calHandler.processInput( "+", 3 );

        assertEquals( new BigDecimal( "46" ), calHandler.getNumbers().peek().getNumber() );
    }

    @Test
    public void testSqrt() {
        RpnCalculatorHandler calHandler = new RpnCalculatorHandler();

        calHandler.processInput( "2", 1 );
        calHandler.processInput( "sqrt", 2 );

        assertEquals( new BigDecimal( "1.414213562373095" ), calHandler.getNumbers().peek().getNumber() );
    }

    @Test
    public void testClear() {
        RpnCalculatorHandler calHandler = new RpnCalculatorHandler();

        calHandler.processInput( "2", 1 );
        calHandler.processInput( "clear", 2 );

        assertEquals( 0, calHandler.getNumbers().size() );
    }

    @Test
    public void testUndo() {
        RpnCalculatorHandler calHandler = new RpnCalculatorHandler();

        calHandler.processInput( "2", 1 );
        calHandler.processInput( "3", 2 );
        calHandler.processInput( "undo", 3 );

        assertEquals( new BigDecimal( "2" ), calHandler.getNumbers().peek().getNumber() );
    }
}
